name: Release Tag

on:
  push:
    branches:
      - master

env:
  SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/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"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: 버전 정보 추출
        run: echo "##[set-output name=version;]$(echo '${{ github.event.head_commit.message }}' | egrep -o 'v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')"
        id: extract_version_name    

      - name: Release 생성 
        uses: actions/create-release@latest
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          tag_name: ${{ steps.extract_version_name.outputs.version }} 
          release_name: ${{ steps.extract_version_name.outputs.version }} 

      # - name: action-slack
        # uses: 8398a7/action-slack@v3
        # with:
        #   status: ${{ job.status }}
        #   author_name: ${{ github.event.inputs.deploy_env }} docker image ${{ env.SHARED_RESOURCE_PROJECT_ID}} ${{ github.event.inputs.server_name }}
        #   fields: repo, message, commit, author, action, eventName, ref, workflow, job, took
        # env:
        #   SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }}
        # if: always()
